### PR TITLE
chores to clean up + simplify code

### PR DESCRIPTION
**Pull request by khandelwala812**

### CODE REVIEW

**Comment by maxwellmlin** [comment]
Unable to open the popup link anymore, getting this error:

Screen Shot 2021-07-12 at 3 56 41 PM

**Comment by khandelwala812** [comment]
Fixed! The problem was `getElementsByTagName` returns a HTMLCollection, not an array.

**Comment by khandelwala812** [comment]
Decided to keep a consistent DOM selector (`querySelector`/`querySelectorAll`). Also, `querySelectorAll` returns a NodeList, which circumvents the step of converting `links` to an array.

**Comment by maxwellmlin** [comment]
Very nice 👏 thank you!

**Pull request merged**
